apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: circle-api-dev
  namespace: argocd
spec:
  project: workloads
  source:
    repoURL: https://github.com/MassimoDanieli/gitops-workloads.git
    targetRevision: main
    path: charts/circle-api
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: circle-api-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
